version: '3.9'


services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=db
      - DB_USER=postgres
      - DB_PASSWORD=Password
      - DB_PORT=5432
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password
      - STRIPE_SECRET_KEY = "sk_test_75OIDeqJX98bRIkqFDOVr7nTohgsxfpiAl1OVCaIHnzyJRbSEuHavW5hs00N7tiXGJT"
      - STRIPE_PUBLIC_KEY = "pk_test_75OIDeqJX98bRIkqFUzS3lpvZT4mK1mF46DpsUqYN7UoR6ZM5i1iCGuHm000b9yBL0w"

    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: